### ISSUE TITLE
Display Reset is necessary for some TTGO Boards

### ISSUE THREAD

**Issue by stegro** [DO6FP/hamgroup_lorawan#2]
Hallo zusammen,

wir hatten noch zwei von diesen TTGO Boards in der Schublade:
http://www.lilygo.cn/prod_view.aspx?TypeId=50060&Id=1142&FId=t3:50060:3

Damit sind wir zunächst gescheitert, das Display Beispiel
https://github.com/DO6FP/hamgroup_lorawan/blob/main/code/HelloWorld_display/HelloWorld-display.ino
 korrekt zu sehen, d.h. wir konnten kompilieren und flashen aber das Display blieb schwarz.

Es hat sich herausgestellt, dass man das Display jedenfalls für diese Boardversion "resetten" muss, damit es mitarbeitet:

```

// mir nicht genau klar, ob man Wire.h braucht, aber viele scheinen es zu inkluden, wohl um explizit I2C zu definieren.
#include <Wire.h>

#define DISPLAY_RST 16

// ThingPulse OLED SSD1306 - Library
// https://github.com/ThingPulse/esp8266-oled-ssd1306
#include "SSD1306.h"  

// Diese Praeprozessor-makros sind sind schon über die
// Board-Auswahl definiert
SSD1306 display(0x3c, OLED_SDA, OLED_SCL); 

void setup() {
  // reset display with a delay.
  // if this is not done, the display of our TTGO (cf link above) will remain black. I do not know if this is okay for other TTGO boards!
  pinMode(DISPLAY_RST, OUTPUT);

  // set GPIO16 low to reset OLED
  digitalWrite(DISPLAY_RST, LOW);  
  delay(50);
  // while OLED is running, must set GPIO16 in high、
  digitalWrite(DISPLAY_RST, HIGH); 
  
 
  display.init();
  display.flipScreenVertically();
  display.setFont(ArialMT_Plain_10);
}


```

**Comment by FPfannkuch** [comment]
Hallo stegro,
stimmt, da wir unsere Programme für das Board in V2.1x auslegen stand bisher die Unterstützung anderer Boards nicht im Vordergrund (auch wegen mangelnder Testhardware).

**Comment by stegro** [comment]
Wie wäre es mit einem Kommentar und dem Code für den Reset
auskommentiert im setup()?

 - wäre das schon drin bzw bekannt gewesen, dann hätten uns das einen
   Tag Suche gespart... Und so ist es für andere Leute mit älterem Board
   nützlich und weniger frustrierend.

73

Am Sat, 18 Dec 2021 10:31:39 -0800
schrieb DO6FP ***@***.***>:

> Closed #2.
>

**Comment by FPfannkuch** [comment]
Wir haben mit Absicht am Anfang darauf hingewiesen, dass wir die schon genannten Boards unterstützen.
Unser Ziel ist es mit den Scetchen eine Art Kochbuch zu schaffen.
Wenn du Lust und Zeit hast kannst du gerne uns Unterstützen, weitere Boards mit aufzunehmen.
73 de Felix

**Comment by stegro** [comment]
Siehe https://github.com/stegro/hamgroup_lorawan/tree/port-ttgo-v1 .
Ich schicke euch dafür aber keinen Pull Request, da ich nicht sicher bin, ob euch das recht ist.

Ja, ich verstehe das natürlich, dass man nicht alles supporten kann. Aber die Boards v1 und v2 sind für den Neuling äußerlich total ähnlich. Und laut Mailingliste haben nicht nur wir noch eine alte Version v1, die wir ungern wegwerfen wollen.
- Mehr als einen kleinen Hinweis auf den Display Reset im Quelltext braucht es aus meiner Sicht gar nicht.

73 de dm4sg
